# Generated by Django 2.0.3 on 2018-04-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_receiptbotusers_receiptrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptbotusers',
            old_name='chat_id',
            new_name='telegr_chat_id',
        ),
        migrations.RenameField(
            model_name='receiptbotusers',
            old_name='connection_date',
            new_name='telegr_connection_date',
        ),
        migrations.RenameField(
            model_name='receiptbotusers',
            old_name='user_name',
            new_name='telegr_user_name',
        ),
        migrations.RenameField(
            model_name='receiptrequest',
            old_name='chat_id',
            new_name='telegr_chat_id',
        ),
        migrations.RenameField(
            model_name='receiptrequest',
            old_name='user_name',
            new_name='telegr_user_name',
        ),
    ]
